// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiKFPLQil37I6-EkWnS9WzbB0MRPVeFMY',
    appId: '1:972732596176:web:f4114c9d361452a90c83d5',
    messagingSenderId: '972732596176',
    projectId: 'studentdirector-fde32',
    authDomain: 'studentdirector-fde32.firebaseapp.com',
    storageBucket: 'studentdirector-fde32.firebasestorage.app',
    measurementId: 'G-MNT1NLYW7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD41oRYH8BcqiyjiVTG7EibRVpgt452vUs',
    appId: '1:972732596176:android:fc04c2e1b8a7abef0c83d5',
    messagingSenderId: '972732596176',
    projectId: 'studentdirector-fde32',
    storageBucket: 'studentdirector-fde32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSpDWnL595kERBSeQ8ZvNOziZBS2Upg9g',
    appId: '1:972732596176:ios:1381f5cc30f3d74c0c83d5',
    messagingSenderId: '972732596176',
    projectId: 'studentdirector-fde32',
    storageBucket: 'studentdirector-fde32.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSpDWnL595kERBSeQ8ZvNOziZBS2Upg9g',
    appId: '1:972732596176:ios:1381f5cc30f3d74c0c83d5',
    messagingSenderId: '972732596176',
    projectId: 'studentdirector-fde32',
    storageBucket: 'studentdirector-fde32.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiKFPLQil37I6-EkWnS9WzbB0MRPVeFMY',
    appId: '1:972732596176:web:e62249194ff167c00c83d5',
    messagingSenderId: '972732596176',
    projectId: 'studentdirector-fde32',
    authDomain: 'studentdirector-fde32.firebaseapp.com',
    storageBucket: 'studentdirector-fde32.firebasestorage.app',
    measurementId: 'G-FX0C3MYLXX',
  );
}
